- data/leads.toml
also need to update volk once we figure out who's taking over
> updated leads (added josh, removed richard)

- content/grcon/grcon20/charlotte.md
> Charlotte is in North, not South Carolina

- content/blog/2020-07-09-darpa-workshops/index.md
This adds a blog post about the virtual hackfest and subsequent workshops
> blog: add article about workshops with darpa

- content/blog/2016-06-19-pybombs-the-what-the-how-and-the-why/index.md
These old commands are still throwing people off, even with the big warning and link, so I just removed them altogether
> Updated pybombs page

- content/news/2020-09-28-hamradio/index.md
> Revise meeting information

- content/news/2020-05-09-volk-v2.3.0-release/index.md
@duggabe asked me to add this release news. gnuradio.org should be more complete with this news.
> news: Add VOLK 2.3.0 release news

- content/news/2021-06-10-gnu-radio-v3.8.3.1-release/index.md
- content/news/2021-06-10-gnu-radio-v3.9.2.0-release/index.md
Signed-off-by: Jeff Long <willcode4@gmail.com>
> news: 2021-06-10 releases

- content/news/2021-10-09-gnuradio-v3.8.4.0-release/index.md
- content/news/2021-10-09-gnuradio-v3.9.3.0-release/index.md
Signed-off-by: Jeff Long <willcode4@gmail.com>
> news: 2021-09-30 releases

- content/news/2021-10-31-gnuradio-v3.9.4.0-release/index.md
Signed-off-by: Jeff Long <willcode4@gmail.com>
> news: release v3.9.4.0

- content/news/2022-01-17-gnuradio-v3.10.0.0-release/index.md
Signed-off-by: Josh Morman <jmorman@gnuradio.org>
> news: Release v3.10.0.0

- content/news/2022-02-14-grcon22-location-announcement/index.md
Signed-off-by: Josh Morman <jmorman@gnuradio.org>
> news: GRCon22 location announcement

- content/news/2022-03-12-gsoc22-announcement/index.md
> News: GSoC22 accepted

- content/news/2022-03-12-gsoc22-announcement/index.md
> news: Correct GSoC application open date

- themes/gnuradio-bootstrap/layouts/partials/subfoot.html
> Added donation link to footer

- container/Dockerfile
- layouts/event/grcon/list.html
- themes/gnuradio-bootstrap/layouts/partials/base/footer.html
- themes/gnuradio-bootstrap/layouts/partials/base/metas.html
- themes/gnuradio-bootstrap/layouts/partials/homepage.html
This builds, but needs testing of the various places URL generation was altered.
> hugo: Updated version to 0.101.0 and fixed theme

- data/carousel/grcon.yml
Signed-off-by: Josh Morman <jmorman@gnuradio.org>
> Update carousel with grcon23

- content/blog/2023-01-28-pmt_journey/index.md
Signed-off-by: Josh Morman <jmorman@gnuradio.org>
> John's blog post on pmt work

- content/news/2023-01-14-volk-v3.0.0-release/index.md
> volk: Add release 3.0.0 news

- config.yml
removed grcon20 from the events list
Signed-off-by:  Toby Flynn <tflynn@redwiretechnology.com>
> Updated config.yml to include grcon2023 in events menu,

- content/blog/2023-05-24-GSoC-(Week-0)/index.md
Signed-off-by: Rahul Balaji [rahulbalaji78@gmail.com]
> add week-0 GSoC : Standalone GRC blog

- content/blog/2023-06-05-GRC-standalone-week-01/index.md
Signed-off-by: Rahul Balaji rahulbalaji78@gmail.com
> add week-01 blog for GRC: standalone application

- content/blog/2023-06-24-GRC-standalone-week-3/index.md
- content/blog/2023-06-31-GRC-standalone-week-4/index.md
Signed-off-by: Rahul Balaji [rahulbalaji78@gmail.com](mailto:rahulbalaji78@gmail.com)
> added week 3 and week 4 blog for standalone GRC

- content/news/2023-07-19-gnuradio-v3.10.7.0-release/index.md
> news: v3.10.7.0

- content/blog/2023-07-09-GRC-standalone-week-05/index.md
Signed-off-by: Rahul Balaji rahulbalaji78@gmail.com
> add GSOC standalone GRC week-05 blog

- content/blog/2023-07-23-GSoC-2023-Qt-Widgets-Improvement---Week-7/index.md
Purely cosmetic, but greatly increases readability. Should've caught this before merging the blog post. Sorry about that!
> blog: Make GSoC Qt Widgets week 7 list headers bold

- content/blog/2023-06-30-GRC-standalone-week-4/index.md
- content/blog/2023-07-16-GRC-standalone-week-6/index.md
- content/blog/2023-07-23-GRC-standalone-week-7/index.md
Signed-off-by: Rahul Balaji [rahulbalaji78@gmail.com](mailto:rahulbalaji78@gmail.com)
> added blog for week 6 and 7 of standalone GRC

- themes/gnuradio-bootstrap/assets/js/jquery-3.7.0.slim.js
- themes/gnuradio-bootstrap/layouts/partials/base/scripts.html
> Updating to JQuery 3.7.0 in order to silence dependabot alerts

- content/news/2023-11-08-FOSDEM24-CfP/index.md
Due to unforeseen circumstances, no long talks
> CfP: no long talks

- content/blog/tracking-orangutans-with-drones-and-gnu-radio/index.md
> blog entry: fix Orang Utan tracking external URL

- content/blog/2023-12-12-Update-on-the-last-three-months-in-GR/index.md
> Newsletter for 2023-12

- content/news/2023-12-16-grcon24-location-announcement/index.md
- themes/gnuradio-bootstrap/layouts/partials/homepage.html
Didn't render before, because time was in the future, and um, someone was playing with his local hugo and didn't notice on the original content PR
> make grcon24 news entry render

- content/community/_index.md
> For as long as the IRC bridge is not functional, remove content

- config.yml
- content/grcon/grcon25/_index.md
- content/news/2023-12-16-grcon24-location-announcement/index.md
- content/news/2025-02-21-grcon25-location-announcement/index.md
- data/carousel/grcon.yml
> GRCon25 updates

- content/news/2025-02-20-saying-thank-you-to-jeff/index.md
- layouts/_default/single.html
- layouts/partials/page.html
> Thank you, Jeff!
